import React from 'react';
import { useHospital } from '../context/HospitalContext';
import { Mail, X, CheckCircle2, Send, Clock, Inbox } from 'lucide-react';

export const EmailLogModal: React.FC = () => {
  const { showEmailLogModal, setShowEmailLogModal, emailLogs } = useHospital();

  if (!showEmailLogModal) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/70 backdrop-blur-sm">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 w-full max-w-2xl h-[75vh] rounded-3xl shadow-2xl overflow-hidden flex flex-col">
        
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between bg-slate-50 dark:bg-slate-900">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-cyan-600 text-white flex items-center justify-center font-bold">
              <Mail className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base text-slate-900 dark:text-white">
                Nodemailer SMTP System Email Logs
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Simulated outgoing emails generated by backend REST APIs
              </p>
            </div>
          </div>

          <button
            onClick={() => setShowEmailLogModal(false)}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-white"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Email Logs List */}
        <div className="flex-1 overflow-y-auto p-4 divide-y divide-slate-100 dark:divide-slate-800">
          {emailLogs.length === 0 ? (
            <div className="py-12 text-center text-slate-400">
              <Inbox className="w-10 h-10 mx-auto mb-2 opacity-50" />
              <p className="text-xs">No emails sent yet</p>
            </div>
          ) : (
            emailLogs.map(em => (
              <div key={em.id} className="py-3.5 px-2 hover:bg-slate-50 dark:hover:bg-slate-800/40 rounded-xl transition-colors">
                <div className="flex items-center justify-between gap-2 mb-1">
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-cyan-100 text-cyan-800 dark:bg-cyan-950 dark:text-cyan-300">
                      {em.category}
                    </span>
                    <span className="font-bold text-xs text-slate-900 dark:text-white">
                      To: {em.to}
                    </span>
                  </div>
                  <div className="flex items-center gap-1 text-[11px] text-emerald-600 dark:text-emerald-400 font-semibold">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>{em.status}</span>
                  </div>
                </div>

                <h4 className="font-semibold text-xs text-slate-800 dark:text-slate-200 mt-1">
                  Subject: {em.subject}
                </h4>
                
                <p className="text-xs text-slate-600 dark:text-slate-400 mt-1 leading-relaxed bg-slate-100/70 dark:bg-slate-800/80 p-2.5 rounded-lg font-mono">
                  {em.body}
                </p>

                <span className="text-[10px] text-slate-400 mt-1.5 block">
                  Sent via Nodemailer SMTP on {em.sentAt}
                </span>
              </div>
            ))
          )}
        </div>

      </div>
    </div>
  );
};
